# CMake generated Testfile for 
# Source directory: I:/PIME/libIME2/test
# Build directory: I:/PIME/build_probe64/libIME2/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ComPtr_test "I:/PIME/build_probe64/libIME2/test/Debug/ComPtr_test.exe")
  set_tests_properties(ComPtr_test PROPERTIES  _BACKTRACE_TRIPLES "I:/PIME/libIME2/test/CMakeLists.txt;5;add_test;I:/PIME/libIME2/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ComPtr_test "I:/PIME/build_probe64/libIME2/test/Release/ComPtr_test.exe")
  set_tests_properties(ComPtr_test PROPERTIES  _BACKTRACE_TRIPLES "I:/PIME/libIME2/test/CMakeLists.txt;5;add_test;I:/PIME/libIME2/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ComPtr_test "I:/PIME/build_probe64/libIME2/test/MinSizeRel/ComPtr_test.exe")
  set_tests_properties(ComPtr_test PROPERTIES  _BACKTRACE_TRIPLES "I:/PIME/libIME2/test/CMakeLists.txt;5;add_test;I:/PIME/libIME2/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ComPtr_test "I:/PIME/build_probe64/libIME2/test/RelWithDebInfo/ComPtr_test.exe")
  set_tests_properties(ComPtr_test PROPERTIES  _BACKTRACE_TRIPLES "I:/PIME/libIME2/test/CMakeLists.txt;5;add_test;I:/PIME/libIME2/test/CMakeLists.txt;0;")
else()
  add_test(ComPtr_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ComObject_test "I:/PIME/build_probe64/libIME2/test/Debug/ComObject_test.exe")
  set_tests_properties(ComObject_test PROPERTIES  _BACKTRACE_TRIPLES "I:/PIME/libIME2/test/CMakeLists.txt;9;add_test;I:/PIME/libIME2/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ComObject_test "I:/PIME/build_probe64/libIME2/test/Release/ComObject_test.exe")
  set_tests_properties(ComObject_test PROPERTIES  _BACKTRACE_TRIPLES "I:/PIME/libIME2/test/CMakeLists.txt;9;add_test;I:/PIME/libIME2/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ComObject_test "I:/PIME/build_probe64/libIME2/test/MinSizeRel/ComObject_test.exe")
  set_tests_properties(ComObject_test PROPERTIES  _BACKTRACE_TRIPLES "I:/PIME/libIME2/test/CMakeLists.txt;9;add_test;I:/PIME/libIME2/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ComObject_test "I:/PIME/build_probe64/libIME2/test/RelWithDebInfo/ComObject_test.exe")
  set_tests_properties(ComObject_test PROPERTIES  _BACKTRACE_TRIPLES "I:/PIME/libIME2/test/CMakeLists.txt;9;add_test;I:/PIME/libIME2/test/CMakeLists.txt;0;")
else()
  add_test(ComObject_test NOT_AVAILABLE)
endif()
